# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: 4orm

before:
  hooks:
    - go mod tidy

builds:
  - id: 4orm
    main: ./cmd/4orm
    binary: 4orm
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: 4orm
    ids:
      - 4orm
    name_template: "4orm-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - none*

checksum:
  name_template: "4orm_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
