"""add oauth2 tables

Revision ID: de7c5007c2f0
Revises: 1b95581dfedd
Create Date: 2026-04-26 23:51:29.490635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7c5007c2f0'
down_revision: Union[str, Sequence[str], None] = '1b95581dfedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('client_secret', sa.String(length=120), server_default='', nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('redirect_uris', sa.Text(), server_default='', nullable=False),
    sa.Column('scope', sa.Text(), server_default='', nullable=False),
    sa.Column('grant_types', sa.Text(), server_default='authorization_code', nullable=False),
    sa.Column('response_types', sa.Text(), server_default='code', nullable=False),
    sa.Column('token_endpoint_auth_method', sa.String(length=48), server_default='client_secret_basic', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('oauth2_authorization_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), server_default='', nullable=False),
    sa.Column('scope', sa.Text(), server_default='', nullable=False),
    sa.Column('nonce', sa.String(length=120), nullable=True),
    sa.Column('code_challenge', sa.Text(), nullable=True),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('oauth2_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.String(length=40), server_default='bearer', nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.Text(), server_default='', nullable=False),
    sa.Column('issued_at', sa.Integer(), nullable=False),
    sa.Column('expires_in', sa.Integer(), server_default='3600', nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.drop_table('galleries')
    op.drop_table('gallery_items')
    op.create_unique_constraint('uq_push_user_device', 'push_subscriptions', ['user_id', 'device_id'])
    op.create_foreign_key(None, 'users', 'invites', ['invite_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('uq_push_user_device', 'push_subscriptions', type_='unique')
    op.create_table('gallery_items',
    sa.Column('gallery_id', sa.INTEGER(), nullable=False),
    sa.Column('media_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gallery_id', 'media_id')
    )
    op.create_table('galleries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('oauth2_tokens')
    op.drop_table('oauth2_authorization_codes')
    op.drop_table('oauth2_clients')
    # ### end Alembic commands ###
